---
# playbook

- name: Despliegue de servidor web sobre un contenedor de Podman sobre máquina virtual de Azure
  hosts: all
  gather_facts: true
  become: true
 
  tasks:
    # INSTALACIONES PREVIAS

    - name: Instalacion de dependencias y herrarramientas necesarias para el despliegue
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - httpd-tools
        - openssl
        - python3
        - python3-pip

    - name: Instalacion de Podman en el nodo gestionado
      yum:
        name: podman
        state: present

    - name: Instalacion de passlib mediante pip
      ansible.builtin.pip:
        name: passlib
        state: present
        executable: pip3
      become: true

    # PREPARACION Y CREACION IMAGEN

    - name: Crear directorio donde residiran los archivos para construir la imagen
      ansible.builtin.file:
        path: webserver
        state: directory
        mode: '0755'
    
    - name: Crear archivo .creds con credenciales para acceder al servicio web
      community.general.htpasswd:
        path: webserver/.creds
        name: testuser
        password: lotuslotus
        crypt_scheme: bcrypt
        create: yes

    # Hay que asegurarse de tener instalado el paquete community.crypto en nodo de control (#ansible-galaxy collection install community.general)
    - name: Generar clave privada
      community.crypto.openssl_privatekey:
        path: webserver/localhost.key
        type: RSA
        size: 2048

    - name: Generar solicitud de certificado
      community.crypto.openssl_csr:
        privatekey_path: webserver/localhost.key
        path: webserver/localhost.csr
        common_name: vm1
        country_name: ES
        state_or_province_name: Madrid
        locality_name: Madrid
        organization_name: DevOps
        organizational_unit_name: Ejemplo

    - name: Firmar solicitud de certificado
      community.crypto.x509_certificate:
        path: webserver/localhost.crt
        csr_path: webserver/localhost.csr
        privatekey_path: webserver/localhost.key
        provider: selfsigned

    - name: Copiar archivos del nodo de control al directorio webserver de la máquina virtual 
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "webserver/{{ item.dest }}"
        mode: '0644'
        remote_src: false
      with_items:
        - { src: "index.html", dest: "index.html" }
        - { src: "httpd.conf", dest: "httpd.conf" }
        - { src: "Containerfile", dest: "Containerfile" }
        - { src: ".htaccess", dest: ".htaccess" }

# Hay que asegurarse de tener instalado el paquete containers.podman en nodo de control (# ansible-galaxy collection install containers.podman)

    - name: Construir la imagen del webserver a partir de todos los ficheros anteriores
      containers.podman.podman_image:
        name: webserver
        path: webserver

    - name: Añadir la etiqueta casopractico2 a la imagen
      containers.podman.podman_tag:
        image: localhost/webserver:latest
        target_names: 
          - registrodavid.azurecr.io/webserver:casopractico2

    # SUBIDA AL REGISTRY DE AZURE

    - name: Login al registry
      containers.podman.podman_login:
        username: registrodavid
        password: '5iuy6gP/PtGbixfbKzfOo2kTT0oJRSkMIe2fR/H72a+ACRCl2frA'
        registry: registrodavid.azurecr.io/webserver

    - name: Realizar el push de la imagen al registry
      become: true
      containers.podman.podman_image:
        name: registrodavid.azurecr.io/webserver:casopractico2
        push: true

    # CREACION DEL CONTENEDOR

    - name: Crear contenedor a partir de la imagen del registry
      containers.podman.podman_container:
        name: web
        image: registrodavid.azurecr.io/webserver:casopractico2
        ports:
          - "8080:443"

    - name: Generar como servicio del SO
      ansible.builtin.systemd:
        name: web.service
        state: started
        enabled: true

      
