---
# playbook



- name: Instalación de una aplicación (MongoDB) con almacenamiento persistente sobre un cluster AKS
  hosts: all
  gather_facts: true
  become: true

  vars:
    ansible_python_interpreter: /bin/python3
 
  tasks:
    # INSTALACIONES PREVIAS

    - name: Instalar dependencias y herramientas
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - httpd-tools
        - openssl
        - python3
        - python3-pip

    - name: Instalar Podman
      yum:
        name: podman
        state: present

    - name: Crear directorio
      ansible.builtin.file:
        path: mongo
        state: directory
        mode: '0755'
    
# Hay que tener instalado el paquete containers.podman en nodo de control (# ansible-galaxy collection install containers.podman)

    # CREACION DE LA IMAGEN
    
    - name: Traer imagen de mongodb desde docker.hub usando Podman
      containers.podman.podman_image:
        name: mongo

    - name: Añadir tag a la imagen
      containers.podman.podman_tag:
        image: mongo:latest
        target_names: 
          - registrodavid.azurecr.io/mongo:casopractico2

    # SUBIDA AL REGISTRY DE AZURE

    - name: Login al registry
      containers.podman.podman_login:
        username: registrodavid
        password: '5iuy6gP/PtGbixfbKzfOo2kTT0oJRSkMIe2fR/H72a+ACRCl2frA'
        registry: registrodavid.azurecr.io/mongo

    - name: Realizar push de la imagen al registry
      become: true
      containers.podman.podman_image:
        name: registrodavid.azurecr.io/mongo:casopractico2
        push: true

    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: mongo
        api_version: v1
        kind: Namespace
        state: present

    - name: Create el deployment y el servicio desde un fichero 
      kubernetes.core.k8s:
        state: present
        src: app_mongo.yaml
    
