---
- name: Conexión SSH y despliegue de herramientas
  hosts: azure
  gather_facts: true
  become: true
  tasks:
    - name: Conexión SSH a la máquina virtual
      ansible.builtin.shell: ssh azureuser@192.168.1.5
      delegate_to: localhost

    - name: Instalar Podman, httpd-tools y openssl
      package:
        name:
          - podman
          - httpd-tools
          - openssl
        state: present

    - name: Crear directorio webserver
      file:
        path: /home/user/webserver
        state: directory
        owner: user
        group: user
        mode: '0755'
